# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "Ujwala", password: "123456")
User.create(username: "John", password: "123456")
User.create(username: "Jane", password: "123456")
User.create(username: "Ross", password: "123456")
User.create(username: "Miller", password: "123456")
User.create(username: "Kate", password: "123456")
User.create(username: "Tina", password: "123456")
User.create(username: "Smith", password: "123456")
User.create(username: "Ron", password: "123456")
User.create(username: "Tom", password: "123456")
User.create(username: "Sheila", password: "123456")
User.create(username: "Michael", password: "123456")
User.create(username: "Nick", password: "123456")
User.create(username: "Donald", password: "123456")
User.create(username: "Bill", password: "123456")
User.create(username: "Reza", password: "123456")
User.create(username: "Munis", password: "123456")
User.create(username: "Emma", password: "123456")
User.create(username: "Lucas", password: "123456")
User.create(username: "Liam", password: "123456")
User.create(username: "Noah", password: "123456")
User.create(username: "Lia", password: "123456")
User.create(username: "Tia", password: "123456")
User.create(username: "Olivia", password: "123456")
User.create(username: "Mason", password: "123456")
User.create(username: "Riley", password: "123456")
User.create(username: "Zoe", password: "123456")
User.create(username: "Oliver", password: "123456")
User.create(username: "Jacob", password: "123456")
User.create(username: "Lily", password: "123456")
User.create(username: "Ben", password: "123456")
User.create(username: "Chole", password: "123456")
User.create(username: "Caleb", password: "123456")
User.create(username: "Carter", password: "123456")
User.create(username: "Ryan", password: "123456")
User.create(username: "Abigail", password: "123456")
User.create(username: "Owen", password: "123456")
User.create(username: "Sarah", password: "123456")
User.create(username: "Andrew", password: "123456")
User.create(username: "Lilian", password: "123456")
User.create(username: "guest", password: "123456")


Business.create(name: "Happy Smiles", description: "Complete Dental care for the Family", street_address: "160 spear st", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-989-6100", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484330239/clinic1_ouv2ym.png", latitude: 37.791518, longitude: -122.393689)
Business.create(name: "Golden Gate Dental Care", description: "Your friendly neighbourhood dentist", street_address: "225 Onondaga Ave", city_state_address: "San Francisco, CA", zipcode: "94112", phone: "415-234-3234", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484251468/clinic2_g9awb4.jpg", latitude: 37.722850, longitude: -122.441918)
Business.create(name: "Melissa Cosmetic Dental Care", description: "Dental care you can trust!", street_address: "146 Prague St", city_state_address: "San Francisco, CA", zipcode: "94112", phone: "415-980-2334", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327614/clinic3_m8vfwn.jpg", latitude: 37.719986, longitude: -122.426834)
Business.create(name: "Ocean Beach Dental", description: "Giving your smile back", street_address: "225 Marina Blvd", city_state_address: "San Francisco, CA", zipcode: "94123", phone: "415-223-6278", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327618/clinic4_rmgxat.jpg", latitude: 37.806418, longitude: -122.436170)
Business.create(name: "Tooth Friendly", description: "Children dental specialist", street_address: "1690 Valencia St", city_state_address: "San Francisco, CA", zipcode: "94110", phone: "415-363-8388", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327622/clinic5_undemx.jpg", latitude: 37.746508, longitude: -122.420410)
Business.create(name: "Johnson Dental Care", description: "Professional and reliable dental care", street_address: "1444 Union St", city_state_address: "San Francisco, CA", zipcode: "94109", phone: "415-123-7828", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327625/clinic6_xy3byh.jpg", latitude: 37.799066, longitude: -122.423141)
Business.create(name: "Downtown Dental", description: "Best Pedrictic Dentist in town", street_address: "1336 Polk St", city_state_address: "San Francisco, CA", zipcode: "94109", phone: "415-452-6541", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327628/clinic7_kjiwrn.jpg", latitude: 37.789531, longitude: -122.420186)
Business.create(name: "Comfort Dental care", description: "Taking care of your comfort", street_address: "1991 California St", city_state_address: "San Francisco, CA", zipcode: "94109", phone: "415-329-8856", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327631/clinic8_am0h4j.jpg", latitude: 37.789729, longitude: -122.427227)
Business.create(name: "Your Smile Dental", description: "Putting a smile on your face", street_address: "9 Palm Ave", city_state_address: "San Francisco, CA", zipcode: "94118", phone: "415-778-9987", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484328309/clinic9_mtnbi6.jpg", latitude: 37.785733, longitude: -122.458374)
Business.create(name: "Pearl Dental Care", description: "Teeth whitening experts", street_address: "1770 Fulton St,", city_state_address: "San Francisco, CA", zipcode: "94117", phone: "415-887-2343", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484327637/clinic10_gxgr1k.jpg", latitude: 37.776398, longitude: -122.446218)

Business.create(name: "Jennifer Family Dentistry", description: "Complete Dental care for the Family", street_address: "101 27th Ave", city_state_address: "San Francisco, CA", zipcode: "94121", phone: "415-421-6109", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918155/clinic11_xcj0ul.jpg", latitude: 37.787417, longitude: -122.487598)
Business.create(name: "Quality Dental Care", description: "Your smile is very important to us", street_address: "6909 Geary Blvd", city_state_address: "San Francisco, CA", zipcode: "94121", phone: "415-909-3778", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918268/clinic12_zsudxf.jpg", latitude: 37.779654, longitude: -122.493550)
Business.create(name: "Abigail Family Dental Care", description: "Dental care you can trust!", street_address: "419 20th Ave", city_state_address: "San Francisco, CA", zipcode: "94121", phone: "415-212-2094", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918511/clinic13_hl0bz7.jpg", latitude: 37.780112, longitude: -122.479639)
Business.create(name: "Smiles R US", description: "Giving your smile back", street_address: "3319 Balboa St", city_state_address: "San Francisco, CA", zipcode: " 94121", phone: "415-990-6789", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918663/clinic14_m50elg.jpg", latitude: 37.775945, longitude:  -122.494456)
Business.create(name: "Keep Smiling", description: "Hi Tech Dental Care ", street_address: "1418 23rd Ave", city_state_address: "San Francisco, CA", zipcode: " 94122", phone: "415-363-8388", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918785/clinic15_pkckwd.jpg", latitude: 37.761286, longitude: -122.480921)
Business.create(name: "Star Dental", description: "Professional and reliable dental care", street_address: "1505 7th Ave", city_state_address: "San Francisco, CA", zipcode: "94122", phone: "415-444-7828", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484918913/clinic16_ls5ckt.jpg", latitude: 37.760253, longitude: -122.464107)
Business.create(name: "Excel Dental", description: "Dental care in the hands of a true professional", street_address: "2224 Rivera St", city_state_address: "San Francisco, CA", zipcode: "94116", phone: "415-452-6541", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484919080/cilnic17_hnrvt0.jpg", latitude: 37.746194, longitude: -122.490357)
Business.create(name: "Stephen Jackson Dental", description: "Taking care of your comfort", street_address: "2700 Ocean Ave", city_state_address: "San Francisco, CA", zipcode: "94132", phone: "415-345-8246", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484919227/clinic18_pyeuog.jpg", latitude: 37.732963, longitude: -122.475303)
Business.create(name: "Kevin Family Dentistry", description: "Putting a smile on your face", street_address: "553 Buckingham Way", city_state_address: "San Francisco, CA", zipcode: "94132", phone: "415-778-9987", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/c_scale,h_213/v1484919524/clinic19_qmkrou.jpg", latitude: 37.730376, longitude: -122.477544)
Business.create(name: "A Plus Dental Care", description: "Whiten your smile with us.", street_address: "821 Grafton Ave", city_state_address: "San Francisco, CA", zipcode: "94112", phone: "415-887-6643", business_image_url: "https://res.cloudinary.com/dzmqqopi9/image/upload/v1484919528/clinic20_z3zghh.jpg", latitude: 37.719867, longitude: -122.461680)

Tag.create(name: "Cosmetic Dentistry")
Tag.create(name: "General Dentistry")
Tag.create(name: "Pediatric Dentistry")
Tag.create(name: "Endodontist")
Tag.create(name: "Orthodontist")
Tag.create(name: "Periodontist")
Tag.create(name: "Oral & Maxillofacial Surgeon")

Tagging.create(business_id: 1, tag_id: 2 )
Tagging.create(business_id: 1, tag_id: 3 )
Tagging.create(business_id: 1, tag_id: 4 )
Tagging.create(business_id: 2, tag_id: 2 )
Tagging.create(business_id: 3, tag_id: 1 )
Tagging.create(business_id: 4, tag_id: 2 )
Tagging.create(business_id: 4, tag_id: 5 )
Tagging.create(business_id: 4, tag_id: 6 )
Tagging.create(business_id: 5, tag_id: 2 )
Tagging.create(business_id: 6, tag_id: 5 )
Tagging.create(business_id: 7, tag_id: 3 )
Tagging.create(business_id: 8, tag_id: 2 )
Tagging.create(business_id: 8, tag_id: 6 )
Tagging.create(business_id: 8, tag_id: 7 )
Tagging.create(business_id: 9, tag_id: 7 )
Tagging.create(business_id: 9, tag_id: 5 )
Tagging.create(business_id: 10, tag_id: 5 )
Tagging.create(business_id: 10, tag_id: 6 )
Tagging.create(business_id: 10, tag_id: 2 )
Tagging.create(business_id: 11, tag_id: 2 )
Tagging.create(business_id: 11, tag_id: 3 )
Tagging.create(business_id: 11, tag_id: 4 )
Tagging.create(business_id: 12, tag_id: 2 )
Tagging.create(business_id: 12, tag_id: 3 )
Tagging.create(business_id: 12, tag_id: 4 )
Tagging.create(business_id: 13, tag_id: 2 )
Tagging.create(business_id: 13, tag_id: 3 )
Tagging.create(business_id: 13, tag_id: 4 )
Tagging.create(business_id: 13, tag_id: 5 )
Tagging.create(business_id: 14, tag_id: 2 )
Tagging.create(business_id: 14, tag_id: 3 )
Tagging.create(business_id: 14, tag_id: 4 )
Tagging.create(business_id: 14, tag_id: 5 )
Tagging.create(business_id: 15, tag_id: 1 )
Tagging.create(business_id: 15, tag_id: 2 )
Tagging.create(business_id: 15, tag_id: 3 )
Tagging.create(business_id: 15, tag_id: 4 )
Tagging.create(business_id: 15, tag_id: 5 )
Tagging.create(business_id: 15, tag_id: 6 )
Tagging.create(business_id: 15, tag_id: 7 )
Tagging.create(business_id: 16, tag_id: 2 )
Tagging.create(business_id: 16, tag_id: 3 )
Tagging.create(business_id: 16, tag_id: 4 )
Tagging.create(business_id: 16, tag_id: 5 )
Tagging.create(business_id: 17, tag_id: 2 )
Tagging.create(business_id: 17, tag_id: 3 )
Tagging.create(business_id: 17, tag_id: 4 )
Tagging.create(business_id: 17, tag_id: 5 )
Tagging.create(business_id: 18, tag_id: 3 )
Tagging.create(business_id: 18, tag_id: 4 )
Tagging.create(business_id: 18, tag_id: 5 )
Tagging.create(business_id: 19, tag_id: 2 )
Tagging.create(business_id: 19, tag_id: 3 )
Tagging.create(business_id: 19, tag_id: 4 )
Tagging.create(business_id: 19, tag_id: 5 )
Tagging.create(business_id: 20, tag_id: 1 )
Tagging.create(business_id: 20, tag_id: 2 )









BusinessInfo.create(business_id: 1, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 2, by_appointment_only: "yes",accept_insurance: "yes")
BusinessInfo.create(business_id: 3, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes" )
BusinessInfo.create(business_id: 4, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 5, accept_credit_card: "yes", by_appointment_only: "yes")
BusinessInfo.create(business_id: 6, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 7, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 8, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 9, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 10, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 11, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 12, by_appointment_only: "yes",accept_insurance: "yes")
BusinessInfo.create(business_id: 13, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes" )
BusinessInfo.create(business_id: 14, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 15, accept_credit_card: "yes", by_appointment_only: "yes")
BusinessInfo.create(business_id: 16, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 17, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 18, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 19, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 20, by_appointment_only: "yes", accept_insurance: "yes")

Review.create(user_id: 1, business_id: 1, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 2, business_id: 1, content: "I've been coming to Dr's office around five years. It is located near Washington Hospital in a small plaza. It can be difficult to find parking right in front of the office, but there is plenty more around the side. There is a small, brightly lit waiting room with a couple couches to flip through the mags or watch the large TV. This morning I arrived on the dot for my scheduled appointment, but I guess a other people wanted to get the turkey and cranberry out of their teeth too. I waited about eight minutes before I was seen. I think Eva is the name of the dental assistant that does the routine checkups. She is friendly and shares amusing stories while you have three things sticking in your mouth. I remember when I first started coming in, she used to talk to me like a grade schooler. Dude, I'm old enough to drink! I was happy she dropped that tone the next few visits, and it's not a problem anymore.", rating: 3.9)
Review.create(user_id: 3, business_id: 1, content: "After searching for the right dental doc i choose this location because of the good reviews. Im terrified and traumatized since i was 13 of coming to the dentist. My first impression was great, they did a full walk through of the office and they all introduced themselves to me. Before doing work on me they went through the whole billing and price with insurance cost witch i thought was great that way i wouldn't be shocked.i had an amazing first experience with Dr . She is amazing at wat she does. She made me feel very comfortable and made me feel that i was in good hands. My whole family wants to transition to this dental office now.i can't wait to finish and have pretty amazing teeth.", rating: 3.2)
Review.create(user_id: 4, business_id: 1, content: "So far so great! Called yesterday to make an appointment for today because I was swollen like a hampster who just shoved his dinner in his mouth and in pain from an infection from a broken filling I had 20 years ago which it's hard to get an appointment that quick as a new patient but they made it work. When I got in, I was walked around the office and was introduced to the whole staff and shown all their machines which is a nice touch and makes you feel like you're being shown your new apartment. I don't remember everyone's names because I was kinda nervous (who isn't? It's the dentist,  not a house party) but I'll tell you that everyone was really nice. After x-rays and some cool camera thing I was shown some things that needed to be fixed which I knew I had issues. Then Dr comes and talks to me about things I needed done and she took care of the deep cleaning herself. She has such gentle hands that I was surprised that I didn't want to punch myself in the face from pain. Need to come back for more work and Dr gave me advice and some prescriptions for the infection. Once again, such a great staff and they don't pressure you to do anything. They even stayed past their lunch to work with me. I met Dr's husband and I can tell that we could have a beer together and laugh about things. Thanks Dr and the awesome staff! Will recommend to anyone I know and anyone reading this.", rating: 2.5)
Review.create(user_id: 5, business_id: 1, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 1, content: "I really like the dental service I get here. They are up to date in their technology and even show modern explanation videos. At my old dentist, they were still showing demo videos from the 80s!  They also give you safety glasses so when they're working on your teeth things won't splash in your eyes, which I'm really grateful for cuz I don't want gunk to be all up in my eyes! The staff here is very friendly and gentle. The first time I came here, I haven't been to the dentist in a while so I had A LOT of cavities. They managed to fill them in in only 3 sessions. I used to be very afraid of the dentist because I had a bad experience when I was little. They were very understanding and worked gently on me when it came time for the numbing injection. Overall this dentistry is friendly, understanding, and I would definitely come back here for cleanings and fillings!", rating: 4.0)
Review.create(user_id: 7, business_id: 1, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 8, business_id: 1, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 1, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 10, business_id: 1, content: "I love this place Dr is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 11, business_id: 2, content: "I was able to book for an appointment just to see the service of this Dental Care Clinic.  My Dentist before rarely find time to see and check what  my concerns are for a follow up appointments, since at most occasions it was usually being followed by the Dentist Assistant and their Hygienist.  Was convinced though that my concerns were just relayed or forwarded to my Dentist at that time until I came to see Dr.  In this Clinic, Dr   tries her best to see her clients even for a mere question or concern of a follow up appointment. It's a great experience that's why I opted to write my review even though I don't typically make reviews in the past. Her staff are friendly too who needs same commendation. Superb and five stars does fit for this Clinic. Extremely impressive plus state of the art device/equipment  which made it absolutely favored for today's technology.  Final word -AWESOME", rating: 5.0)
Review.create(user_id: 12, business_id: 2, content: "This guy is just wants your money and doesn't care about your health. Not only did I have a not-so-great experience, my dad had a terrible one. Would give this guy negative stars if I could. We were fooled by the reviews on here.  My dad went here and Dr. Lim told him he needed a root canal done. Dr. Lim not only did work on him and billed his insurance a ton, he also referred him to a friend of his and had him do a root canal. My dad was in tremendous pain for weeks as a result of it, and when the pain was not subsiding, he went to another dentist someone recommended to him, to see what was going on and to remedy the situation. When he went, the dentist told him that the root canal was never necessary in the first place...needless to say, my dad was infuriated that something completely unnecessary, so painful and costly was done on him, compromising a tooth that didn't need to be. ", rating: 3.9)
Review.create(user_id: 13, business_id: 2, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 14, business_id: 2, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 2, content: "I've consulted other dentists with regards to a complex situation (a cavity on a tooth that has another filling already), and I was only comfortable with getting it done here after talking to the 2 other dentists in the bay. You should go here because: - they will remove the least possible from your tooth in order to make your teeth to last you longest. *Other dentist shops* were inclined to chop of half of my tooth and put a crown. I guess they want to milk my insurance on the expense of my long term health.  - they have great education and are properly trained. They talk you through what they are doing (perfect for a science-driven person like myself) - they have the best tools and machinery. I won't go elsewhere!", rating: 5.0)
Review.create(user_id: 16, business_id: 2, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 17, business_id: 2, content: "This is a great family dentist practice! High tech equipment, friendly, knowledgeable staff (that are great with kids!), welcoming waiting area with coffee, tea and hot chocolate, and helpful appointment reminders.  I also appreciate how they'll work with your insurance company to give you an estimate of any procedures beforehand.  They're also very thorough with their exams and will make recommendations but aren't pushy or do a heavy sales job about it. (We've had a bad experience with a past dentist office that did that!)  My husband, myself and our two younger boys have been going there for 3 years now and been very happy with them!", rating: 5.0)
Review.create(user_id: 18, business_id: 2, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 2, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 20, business_id: 2, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 1, business_id: 3, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 2, business_id: 3, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 3, business_id: 3, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 3, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 3, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 3, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 3, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 3, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 3, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 3, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 11, business_id: 4, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 12, business_id: 4, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 13, business_id: 4, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 14, business_id: 4, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 4, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 4, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 17, business_id: 4, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 4, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 4, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 20, business_id: 4, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 5, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 5, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 3, business_id: 5, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 4, business_id: 5, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 5, business_id: 5, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 5, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 7, business_id: 5, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 5, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 9, business_id: 5, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 10, business_id: 5, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 11, business_id: 6, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 12, business_id: 6, content: "Always a pleasure going to my appointments Dr. John Doe is awesome and I love that he's a perfectionist.", rating: 3.9)
Review.create(user_id: 13, business_id: 6, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 14, business_id: 6, content: "Went in for a routine teeth cleaning and Dr. John Doe and his staff took such great care of me.  Everyone was very professional and very thorough.  I also had a cavity filled", rating: 2.5)
Review.create(user_id: 15, business_id: 6, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 16, business_id: 6, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 17, business_id: 6, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 18, business_id: 6, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 6, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 20, business_id: 6, content: "I love this place Dr. John Doe is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 1, business_id: 7, content: "I love this place, clean and friendly stuff. I like the manager he's such a sweetheart.", rating: 5.0)
Review.create(user_id: 2, business_id: 7, content: "Love this dentist office They are always so friendly and efficient!", rating: 3.9)
Review.create(user_id: 3, business_id: 7, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 7, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 7, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 7, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 7, content: "All dentists ought to take a lesson here!", rating: 5.0)
Review.create(user_id: 8, business_id: 7, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 7, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 10, business_id: 7, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 11, business_id: 8, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 12, business_id: 8, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 13, business_id: 8, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 14, business_id: 8, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 8, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 8, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 17, business_id: 8, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 8, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 8,  content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 20, business_id: 8, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 1, business_id: 9, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 9, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 3, business_id: 9, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 9, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 9, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 9, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 4, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 4, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 4, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 4, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 11, business_id: 10, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 12, business_id: 10, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 13, business_id: 10, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 14, business_id: 10, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 15, business_id: 10, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 5, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 17, business_id: 5, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 5, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 19, business_id: 5, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 20, business_id: 5, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 11, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 2, business_id: 11, content: "I've been coming to Dr's office around five years. It is located near Washington Hospital in a small plaza. It can be difficult to find parking right in front of the office, but there is plenty more around the side. There is a small, brightly lit waiting room with a couple couches to flip through the mags or watch the large TV. This morning I arrived on the dot for my scheduled appointment, but I guess a other people wanted to get the turkey and cranberry out of their teeth too. I waited about eight minutes before I was seen. I think Eva is the name of the dental assistant that does the routine checkups. She is friendly and shares amusing stories while you have three things sticking in your mouth. I remember when I first started coming in, she used to talk to me like a grade schooler. Dude, I'm old enough to drink! I was happy she dropped that tone the next few visits, and it's not a problem anymore.", rating: 3.9)
Review.create(user_id: 3, business_id: 11, content: "After searching for the right dental doc i choose this location because of the good reviews. Im terrified and traumatized since i was 13 of coming to the dentist. My first impression was great, they did a full walk through of the office and they all introduced themselves to me. Before doing work on me they went through the whole billing and price with insurance cost witch i thought was great that way i wouldn't be shocked.i had an amazing first experience with Dr . She is amazing at wat she does. She made me feel very comfortable and made me feel that i was in good hands. My whole family wants to transition to this dental office now.i can't wait to finish and have pretty amazing teeth.", rating: 3.2)
Review.create(user_id: 4, business_id: 11, content: "So far so great! Called yesterday to make an appointment for today because I was swollen like a hampster who just shoved his dinner in his mouth and in pain from an infection from a broken filling I had 20 years ago which it's hard to get an appointment that quick as a new patient but they made it work. When I got in, I was walked around the office and was introduced to the whole staff and shown all their machines which is a nice touch and makes you feel like you're being shown your new apartment. I don't remember everyone's names because I was kinda nervous (who isn't? It's the dentist,  not a house party) but I'll tell you that everyone was really nice. After x-rays and some cool camera thing I was shown some things that needed to be fixed which I knew I had issues. Then Dr comes and talks to me about things I needed done and she took care of the deep cleaning herself. She has such gentle hands that I was surprised that I didn't want to punch myself in the face from pain. Need to come back for more work and Dr gave me advice and some prescriptions for the infection. Once again, such a great staff and they don't pressure you to do anything. They even stayed past their lunch to work with me. I met Dr's husband and I can tell that we could have a beer together and laugh about things. Thanks Dr and the awesome staff! Will recommend to anyone I know and anyone reading this.", rating: 2.5)
Review.create(user_id: 5, business_id: 11, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 11, content: "I really like the dental service I get here. They are up to date in their technology and even show modern explanation videos. At my old dentist, they were still showing demo videos from the 80s!  They also give you safety glasses so when they're working on your teeth things won't splash in your eyes, which I'm really grateful for cuz I don't want gunk to be all up in my eyes! The staff here is very friendly and gentle. The first time I came here, I haven't been to the dentist in a while so I had A LOT of cavities. They managed to fill them in in only 3 sessions. I used to be very afraid of the dentist because I had a bad experience when I was little. They were very understanding and worked gently on me when it came time for the numbing injection. Overall this dentistry is friendly, understanding, and I would definitely come back here for cleanings and fillings!", rating: 4.0)
Review.create(user_id: 7, business_id: 11, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 8, business_id: 11, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 11, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 10, business_id: 11, content: "I love this place Dr is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 11, business_id: 12, content: "I was able to book for an appointment just to see the service of this Dental Care Clinic.  My Dentist before rarely find time to see and check what  my concerns are for a follow up appointments, since at most occasions it was usually being followed by the Dentist Assistant and their Hygienist.  Was convinced though that my concerns were just relayed or forwarded to my Dentist at that time until I came to see Dr.  In this Clinic, Dr   tries her best to see her clients even for a mere question or concern of a follow up appointment. It's a great experience that's why I opted to write my review even though I don't typically make reviews in the past. Her staff are friendly too who needs same commendation. Superb and five stars does fit for this Clinic. Extremely impressive plus state of the art device/equipment  which made it absolutely favored for today's technology.  Final word -AWESOME", rating: 5.0)
Review.create(user_id: 12, business_id: 12, content: "This guy is just wants your money and doesn't care about your health. Not only did I have a not-so-great experience, my dad had a terrible one. Would give this guy negative stars if I could. We were fooled by the reviews on here.  My dad went here and Dr. Lim told him he needed a root canal done. Dr. Lim not only did work on him and billed his insurance a ton, he also referred him to a friend of his and had him do a root canal. My dad was in tremendous pain for weeks as a result of it, and when the pain was not subsiding, he went to another dentist someone recommended to him, to see what was going on and to remedy the situation. When he went, the dentist told him that the root canal was never necessary in the first place...needless to say, my dad was infuriated that something completely unnecessary, so painful and costly was done on him, compromising a tooth that didn't need to be. ", rating: 3.9)
Review.create(user_id: 13, business_id: 12, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 14, business_id: 12, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 12, content: "I've consulted other dentists with regards to a complex situation (a cavity on a tooth that has another filling already), and I was only comfortable with getting it done here after talking to the 2 other dentists in the bay. You should go here because: - they will remove the least possible from your tooth in order to make your teeth to last you longest. *Other dentist shops* were inclined to chop of half of my tooth and put a crown. I guess they want to milk my insurance on the expense of my long term health.  - they have great education and are properly trained. They talk you through what they are doing (perfect for a science-driven person like myself) - they have the best tools and machinery. I won't go elsewhere!", rating: 5.0)
Review.create(user_id: 16, business_id: 12, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 17, business_id: 12, content: "This is a great family dentist practice! High tech equipment, friendly, knowledgeable staff (that are great with kids!), welcoming waiting area with coffee, tea and hot chocolate, and helpful appointment reminders.  I also appreciate how they'll work with your insurance company to give you an estimate of any procedures beforehand.  They're also very thorough with their exams and will make recommendations but aren't pushy or do a heavy sales job about it. (We've had a bad experience with a past dentist office that did that!)  My husband, myself and our two younger boys have been going there for 3 years now and been very happy with them!", rating: 5.0)
Review.create(user_id: 18, business_id: 12, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 12, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 20, business_id: 12, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 1, business_id: 13, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 2, business_id: 13, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 3, business_id: 13, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 13, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 13, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 13, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 13, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 13, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 13, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 13, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 11, business_id: 14, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 12, business_id: 14, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 13, business_id: 14, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 14, business_id: 14, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 14, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 14, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 17, business_id: 14, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 14, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 14, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 20, business_id: 14, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 15, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 15, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 3, business_id: 15, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 4, business_id: 15, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 5, business_id: 15, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 15, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 7, business_id: 15, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 15, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 9, business_id: 15, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 10, business_id: 15, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 11, business_id: 16, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 12, business_id: 16, content: "Always a pleasure going to my appointments Dr. John Doe is awesome and I love that he's a perfectionist.", rating: 3.9)
Review.create(user_id: 13, business_id: 16, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 14, business_id: 16, content: "Went in for a routine teeth cleaning and Dr. John Doe and his staff took such great care of me.  Everyone was very professional and very thorough.  I also had a cavity filled", rating: 2.5)
Review.create(user_id: 15, business_id: 16, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 16, business_id: 16, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 17, business_id: 16, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 18, business_id: 16, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 16, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 20, business_id: 16, content: "I love this place Dr. John Doe is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 1, business_id: 17, content: "I love this place, clean and friendly stuff. I like the manager he's such a sweetheart.", rating: 5.0)
Review.create(user_id: 2, business_id: 17, content: "Love this dentist office They are always so friendly and efficient!", rating: 3.9)
Review.create(user_id: 3, business_id: 17, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 17, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 17, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 17, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 17, content: "All dentists ought to take a lesson here!", rating: 5.0)
Review.create(user_id: 8, business_id: 17, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 17, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 10, business_id: 17, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 11, business_id: 18, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 12, business_id: 18, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 13, business_id: 18, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 14, business_id: 18, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 15, business_id: 18, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 18, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 17, business_id: 18, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 18, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 19, business_id: 18,  content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 20, business_id: 18, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 1, business_id: 19, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 19, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 3, business_id: 19, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 19, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 19, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 19, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 19, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 19, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 19, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 19, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 11, business_id: 20, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 12, business_id: 20, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 13, business_id: 20, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 14, business_id: 20, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 15, business_id: 20, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 16, business_id: 20, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 17, business_id: 20, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 18, business_id: 20, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 19, business_id: 20, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 20, business_id: 20, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)


# Photo Credits
# <li> Logo image created by Oksana Latysheva from Noun Project</li>
# <li> Phone image created by Makhmudkhon from Noun Project</li>
# <li> Map marker image created by Eliricon from Noun Project</li>
# <li> Star image created by Eagle eye from Noun Project</li>
# <li> Zoom image created by Guilhem from Noun Project</li>
# <li> Login Page Background Image from pixabay.com </li>
# <li> Business 1 Image from FreeDigitalPhotos.net </li>
# <li> Business 2 Image from FreeDigitalPhotos.net </li>
# <li> Business 3 Image from FreeDigitalPhotos.net </li>
# <li> Business 4 Image from FreeDigitalPhotos.net </li>
# <li> Business 5 Image from FreeDigitalPhotos.net </li>
# <li> Business 6 Image from FreeDigitalPhotos.net </li>
# <li> Business 7 Image from FreeDigitalPhotos.net </li>
# <li> Business 8 Image from FreeDigitalPhotos.net </li>
# <li> Business 9 Image from FreeDigitalPhotos.net </li>
# <li> Business 10 Image from FreeDigitalPhotos.net </li>
# <li> Business 11 Image from FreeDigitalPhotos.net </li>
# <li> Business 12 Image from FreeDigitalPhotos.net </li>
# <li> Business 13 Image from FreeDigitalPhotos.net </li>
# <li> Business 14 Image from FreeDigitalPhotos.net </li>
# <li> Business 15 Image from FreeDigitalPhotos.net </li>
# <li> Business 16 Image from FreeDigitalPhotos.net </li>
# <li> Business 17 Image from FreeDigitalPhotos.net </li>
# <li> Business 18 Image from FreeDigitalPhotos.net </li>
# <li> Business 19 Image from FreeDigitalPhotos.net </li>
# <li> Business 20 Image from FreeDigitalPhotos.net </li>
