# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(username: "ujwala", password: "123456")
User.create(username: "John", password: "123456")
User.create(username: "Jane", password: "123456")
User.create(username: "Ross", password: "123456")
User.create(username: "Miller", password: "123456")
User.create(username: "Kate", password: "123456")
User.create(username: "Tina", password: "123456")
User.create(username: "Smith", password: "123456")
User.create(username: "Ron", password: "123456")
User.create(username: "Tom", password: "123456")
User.create(username: "guest", password: "123456")


Business.create(name: "Happy Smiles", description: "Complete Dental care for the Family care", street_address: "160 spear st", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-989-600", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484330239/clinic1_ouv2ym.png")
Business.create(name: "Golden Gate Dental Care", description: "Your friendly neighbourhood dentist", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-234-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484251468/clinic2_g9awb4.jpg")
Business.create(name: "Melissa Cosmetic Dental Care", description: "Dental care you can trust!", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327614/clinic3_m8vfwn.jpg")
Business.create(name: "Ocean Beach Dental", description: "Giving your smile back", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327618/clinic4_rmgxat.jpg")
Business.create(name: "Tooth Friendly", description: "Children dental specialist", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327622/clinic5_undemx.jpg")
Business.create(name: "Johnson Dental Care", description: "Professional and reliable dental care", street_address: "160 spear st", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-989-600", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327625/clinic6_xy3byh.jpg")
Business.create(name: "Downtown Dental", description: "Best Pedrictic Dentist in town", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-234-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327628/clinic7_kjiwrn.jpg")
Business.create(name: "Comfort Dental care", description: "Taking care of your comfort", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327631/clinic8_am0h4j.jpg")
Business.create(name: "Your Smile Dental", description: "Putting a smile on your face", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484328309/clinic9_mtnbi6.jpg")
Business.create(name: "Pearl Dental Care", description: "Teeth whitening experts", street_address: "301b Mission St", city_state_address: "San Francisco, CA", zipcode: "94105", phone: "415-980-234", business_image_url: "http://res.cloudinary.com/dzmqqopi9/image/upload/v1484327637/clinic10_gxgr1k.jpg")


BusinessInfo.create(business_id: 1, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 2, by_appointment_only: "yes")
BusinessInfo.create(business_id: 3, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes" )
BusinessInfo.create(business_id: 4, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 5, accept_credit_card: "yes", by_appointment_only: "yes")
BusinessInfo.create(business_id: 6, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 7, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 8, by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 9, accept_credit_card: "yes", by_appointment_only: "yes", accept_insurance: "yes")
BusinessInfo.create(business_id: 10, by_appointment_only: "yes", accept_insurance: "yes")

Review.create(user_id: 1, business_id: 1, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 2, business_id: 1, content: "Always a pleasure going to my appointments Dr. John Doe is awesome and I love that he's a perfectionist.", rating: 3.9)
Review.create(user_id: 3, business_id: 1, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 1, content: "Went in for a routine teeth cleaning and Dr. John Doe and his staff took such great care of me.  Everyone was very professional and very thorough.  I also had a cavity filled", rating: 2.5)
Review.create(user_id: 5, business_id: 1, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 1, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 1, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 8, business_id: 1, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 1, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 10, business_id: 1, content: "I love this place Dr. John Doe is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 1, business_id: 2, content: "I love this place, clean and friendly stuff. I like the manager he's such a sweetheart.", rating: 5.0)
Review.create(user_id: 2, business_id: 2, content: "Love this dentist office They are always so friendly and efficient!", rating: 3.9)
Review.create(user_id: 3, business_id: 2, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 2, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 2, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 2, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 2, content: "All dentists ought to take a lesson here!", rating: 5.0)
Review.create(user_id: 8, business_id: 2, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 2, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 10, business_id: 2, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 1, business_id: 3, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 2, business_id: 3, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 3, business_id: 3, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 3, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 3, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 3, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 3, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 3, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 3, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 3, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 1, business_id: 4, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 4, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 3, business_id: 4, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 4, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 4, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 4, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 4, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 4, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 4, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 4, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 5, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 5, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 3, business_id: 5, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 4, business_id: 5, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 5, business_id: 5, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 5, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 7, business_id: 5, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 5, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 9, business_id: 5, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 10, business_id: 5, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 6, content: "Extremely efficient and very welcoming staff!”", rating: 5.0)
Review.create(user_id: 2, business_id: 6, content: "Always a pleasure going to my appointments Dr. John Doe is awesome and I love that he's a perfectionist.", rating: 3.9)
Review.create(user_id: 3, business_id: 6, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 6, content: "Went in for a routine teeth cleaning and Dr. John Doe and his staff took such great care of me.  Everyone was very professional and very thorough.  I also had a cavity filled", rating: 2.5)
Review.create(user_id: 5, business_id: 6, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 6, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 6, content: "I've been searching for a new dentist and I finally found one. Staff are also great and so welcoming.", rating: 5.0)
Review.create(user_id: 8, business_id: 6, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 6, content: "I'm so so so glad I found this place! I have never met a more friendly, customer service oriented front desk staff! All the ladies I met were smiling, happy and just flat out sweet. They made me feel welcomed the second I entered. ", rating: 3.2)
Review.create(user_id: 10, business_id: 6, content: "I love this place Dr. John Doe is awesome but I'm not happy with the front desk or receptionist she's not freindly and pleasant at al", rating: 2.2)
Review.create(user_id: 1, business_id: 7, content: "I love this place, clean and friendly stuff. I like the manager he's such a sweetheart.", rating: 5.0)
Review.create(user_id: 2, business_id: 7, content: "Love this dentist office They are always so friendly and efficient!", rating: 3.9)
Review.create(user_id: 3, business_id: 7, content: "I recently came here to get my root canal done and the service they provide is simply the best. He is highly skilled and very efficient in his Work", rating: 3.2)
Review.create(user_id: 4, business_id: 7, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 7, content: "Highly recommended!!", rating: 5.0)
Review.create(user_id: 6, business_id: 7, content: "Prompt, great service, professional personnel and a friendly practice", rating: 4.0)
Review.create(user_id: 7, business_id: 7, content: "All dentists ought to take a lesson here!", rating: 5.0)
Review.create(user_id: 8, business_id: 7, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 7, content: "We went in for a consultation and got royal treatment.  The staff is super friendly and all of our questions, and we had many, were answered thoroughly. ", rating: 3.2)
Review.create(user_id: 10, business_id: 7, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.2)
Review.create(user_id: 1, business_id: 8, content: "I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it.”", rating: 5.0)
Review.create(user_id: 2, business_id: 8, content: " I always feel a genuine sense of caring from Dr  and her team. I have my teeth cleaned regularly and have had several teeth filled.", rating: 3.9)
Review.create(user_id: 3, business_id: 8, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 8, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 8, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 8, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 8, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 8, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 8,  content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 8, content: "Bottom line, simply the VERY BEST dental office I've ever had!!", rating: 4.2)
Review.create(user_id: 1, business_id: 9, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 9, content: "A dentist should inspire confidence in his patients, and thats exactly how Dr  earned my reverence. I feel completely taken care of in his office, I trust him with my dental care, my families, and I highly recommend him.", rating: 3.9)
Review.create(user_id: 3, business_id: 9, content: "Everyone is so pleasant and welcoming, they make sure you're comfortable and feeling ok, the Dr is one of the nicest ever. I'm so glad I found this place", rating: 3.2)
Review.create(user_id: 4, business_id: 9, content: "Dr is a very experienced and caring dentist.  He took the time to listen to my wishes and he focused on my priorities. I found his work to be excellent.  I am extremely happy with the service I received.", rating: 2.5)
Review.create(user_id: 5, business_id: 9, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 9, content: "Absolute best dental care I've ever received. Not only is the office absolutely stunning. The doctor was thorough and gentle.", rating: 4.0)
Review.create(user_id: 7, business_id: 4, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 4, content: "The best Staff! The best service! The best Dentist", rating: 4.0)
Review.create(user_id: 9, business_id: 4, content: "Staff are very knowledgeable and accommodating! Great people with good hearts! I highly recommend going to this clinic! ", rating: 3.2)
Review.create(user_id: 10, business_id: 4, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
Review.create(user_id: 1, business_id: 10, content: "This place has always been good to my teeth love the dentists here there are very nice and helpful they treat you like family when you step in the door and I always leave knowing my teeth are clean and ready to go", rating: 5.0)
Review.create(user_id: 2, business_id: 10, content: " I was SUPER scared about dealing with a piece of my molar breaking and falling out. The doctor and his staff were very comforting and helpful.", rating: 3.9)
Review.create(user_id: 3, business_id: 10, content: "Always a great experience from beginning to end. Very professional, knowledgable, friendly staff and Doctor. They take their time to answer all your questions and get to know you. On-time with appointments, I have never had to wait to be ", rating: 3.2)
Review.create(user_id: 4, business_id: 10, content: "Dr. is such a great dentist. He informs you on everything you need to know relating to your visit, gives you various options and most importantly is very patient. ", rating: 2.5)
Review.create(user_id: 5, business_id: 10, content: "Dr was very patient, told me everything I need to know. A great experience", rating: 5.0)
Review.create(user_id: 6, business_id: 5, content: "Thank you for making me feeling at ease during the procedure. Great staff. I wish I had gone to him years ago.", rating: 4.0)
Review.create(user_id: 7, business_id: 5, content: "Great dentist and staff! They are very accommodating with schedules and thorough in their work.  I've had a lot of dental issues and the staff does a great job of explaining the dental issues and costs associated with it", rating: 5.0)
Review.create(user_id: 8, business_id: 5, content: "Great dentist. Modern facilities and comfortable environment. Very gentle and thorough professionals. His staff; hygienist and office and helpful and patient.", rating: 4.0)
Review.create(user_id: 9, business_id: 5, content: "Great experience.  Honest and professional.  I have had a few visits over the past year and can say that they provide consistently good service.  Probably the best experience I've ever had with any dentist. ", rating: 3.2)
Review.create(user_id: 10, business_id: 5, content: "I couldn't ask for a better dentist. Been coming here for a few years now & have always left happy with my visits.", rating: 2.2)
